/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ipl.simulator.ooad;



/**
 *
 * @author prath
 */
public class AuctionDisplay extends javax.swing.JFrame {

    /**
     * Creates new form AuctionDisplay
     */
    //static Functionality fun = Functionality.getInstance();
    static Players One=Players.getInstance();  
    static TimerClass timer=TimerClass.getInstance();
    static BidClass bid=BidClass.getInstance();
    static ButtonStatus Button_Status=ButtonStatus.getInstance();
    static int count=0;
    public AuctionDisplay() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PlayerNameLabel = new javax.swing.JLabel();
        PlayerName = new javax.swing.JLabel();
        CurrentPriceLabel = new javax.swing.JLabel();
        CurrentPriceTeam = new javax.swing.JLabel();
        LastPriceLabel = new javax.swing.JLabel();
        PrevPriceTeam = new javax.swing.JLabel();
        Prev2Price = new javax.swing.JLabel();
        Prev2PriceTeam = new javax.swing.JLabel();
        BidIncrement = new javax.swing.JLabel();
        RemainingPlayers = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        Team1Label = new javax.swing.JLabel();
        Team1Button = new javax.swing.JButton();
        Team2Label = new javax.swing.JLabel();
        Team2Button = new javax.swing.JButton();
        Team3Label = new javax.swing.JLabel();
        Team3Button = new javax.swing.JButton();
        Team4Label = new javax.swing.JLabel();
        Team4Button = new javax.swing.JButton();
        PlayerImageLabel = new javax.swing.JLabel();
        Team1PointsLabel = new javax.swing.JLabel();
        PointsLabel = new javax.swing.JLabel();
        Team3PointsLabel = new javax.swing.JLabel();
        Team4PointsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PlayerBasePrice = new javax.swing.JLabel();
        PlayerNameLabel1 = new javax.swing.JLabel();
        PlayerRole = new javax.swing.JLabel();
        PlayerNameLabel2 = new javax.swing.JLabel();
        PlayerRating = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CurrTeamPrice = new javax.swing.JLabel();
        PrevTeamPrice = new javax.swing.JLabel();
        LastTeamPrice = new javax.swing.JLabel();
        Team1Points = new javax.swing.JLabel();
        Team2Points = new javax.swing.JLabel();
        Team3Points = new javax.swing.JLabel();
        Team4Points = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Team1Purse = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Team2Purse = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Team3Purse = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Team4Purse = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Team2PlayerList = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Team4PlayerList = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Team1PlayerList = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Team3PlayerList = new javax.swing.JTextArea();
        EndBidButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayerNameLabel.setText("Name");

        PlayerName.setText("Player 1");

        CurrentPriceLabel.setText("Current Price");

        CurrentPriceTeam.setText("0");

        LastPriceLabel.setText("Previous Price");

        PrevPriceTeam.setText("0");

        Prev2Price.setText("Last Price");

        Prev2PriceTeam.setText("0");

        BidIncrement.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        BidIncrement.setForeground(new java.awt.Color(51, 51, 255));
        BidIncrement.setText("20");

        RemainingPlayers.setText("Remaining Players");

        Timer.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        Timer.setForeground(new java.awt.Color(51, 51, 255));
        Timer.setText("15");

        Team1Label.setText("Team 1");

        Team1Button.setText("Bid");
        Team1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1ButtonActionPerformed(evt);
            }
        });

        Team2Label.setText("Team 2");

        Team2Button.setText("Bid");
        Team2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2ButtonActionPerformed(evt);
            }
        });

        Team3Label.setText("Team 3");

        Team3Button.setText("Bid");
        Team3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team3ButtonActionPerformed(evt);
            }
        });

        Team4Label.setText("Team 4");

        Team4Button.setText("Bid");
        Team4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team4ButtonActionPerformed(evt);
            }
        });

        PlayerImageLabel.setText("Player Image");

        Team1PointsLabel.setText("Points");

        PointsLabel.setText("Points");

        Team3PointsLabel.setText("Points");

        Team4PointsLabel.setText("Points");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("L");

        PlayerBasePrice.setText("20");

        PlayerNameLabel1.setText("Role");

        PlayerRole.setText("Batsmen");

        PlayerNameLabel2.setText("Rating");

        PlayerRating.setText("50");

        jLabel2.setText("Base Price");

        CurrTeamPrice.setText("None");

        PrevTeamPrice.setText("None");

        LastTeamPrice.setText("None");

        Team1Points.setText("0");

        Team2Points.setText("0");

        Team3Points.setText("0");

        Team4Points.setText("0");

        jLabel7.setText("Purse ");

        Team1Purse.setText("1500");

        jLabel9.setText("Purse ");

        Team2Purse.setText("1500");

        jLabel11.setText("Purse ");

        Team3Purse.setText("1500");

        jLabel13.setText("Purse");

        Team4Purse.setText("1500");

        Team2PlayerList.setColumns(20);
        Team2PlayerList.setRows(5);
        jScrollPane2.setViewportView(Team2PlayerList);

        Team4PlayerList.setColumns(20);
        Team4PlayerList.setRows(5);
        jScrollPane3.setViewportView(Team4PlayerList);

        Team1PlayerList.setColumns(20);
        Team1PlayerList.setRows(5);
        jScrollPane4.setViewportView(Team1PlayerList);

        Team3PlayerList.setColumns(20);
        Team3PlayerList.setRows(5);
        jScrollPane5.setViewportView(Team3PlayerList);

        EndBidButton.setText("End Bid");
        EndBidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndBidButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BidIncrement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Team1Button)
                                    .addComponent(Team1Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Team1PointsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Team1Points))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(Team1Purse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Team2Button)
                                    .addComponent(Team2Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PointsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Team2Points))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(Team2Purse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(Team3Purse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Team3Label)
                                    .addComponent(Team3Button)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Team3PointsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Team3Points))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Team4PointsLabel)
                                                    .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Team4Purse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Team4Points)))
                                            .addComponent(Team4Button)
                                            .addComponent(Team4Label)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(EndBidButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Timer))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlayerNameLabel2)
                                    .addComponent(PlayerNameLabel))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlayerNameLabel1)
                                    .addComponent(jLabel2))
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlayerRating)
                                    .addComponent(PlayerRole)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PlayerName)
                                        .addGap(52, 52, 52)
                                        .addComponent(PlayerImageLabel)
                                        .addGap(51, 51, 51)
                                        .addComponent(RemainingPlayers)))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LastPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CurrentPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Prev2Price)))
                            .addComponent(PlayerBasePrice))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrevPriceTeam)
                        .addGap(18, 18, 18)
                        .addComponent(PrevTeamPrice))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Prev2PriceTeam)
                        .addGap(18, 18, 18)
                        .addComponent(LastTeamPrice))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentPriceTeam)
                        .addGap(18, 18, 18)
                        .addComponent(CurrTeamPrice)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerNameLabel)
                    .addComponent(PlayerName)
                    .addComponent(CurrentPriceLabel)
                    .addComponent(CurrentPriceTeam)
                    .addComponent(PlayerImageLabel)
                    .addComponent(RemainingPlayers)
                    .addComponent(CurrTeamPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastPriceLabel)
                    .addComponent(PrevPriceTeam)
                    .addComponent(PlayerNameLabel1)
                    .addComponent(PlayerRole)
                    .addComponent(PrevTeamPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prev2Price)
                    .addComponent(Prev2PriceTeam)
                    .addComponent(PlayerNameLabel2)
                    .addComponent(PlayerRating)
                    .addComponent(LastTeamPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PlayerBasePrice))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BidIncrement)
                                .addComponent(jLabel1)
                                .addComponent(Timer)
                                .addComponent(EndBidButton))
                            .addGap(41, 41, 41)
                            .addComponent(Team1Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Team1Button)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Team1PointsLabel)
                                .addComponent(Team1Points)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Team3Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Team3Button)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Team3PointsLabel)
                                .addComponent(Team3Points)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Team4Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Team4Button)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Team4PointsLabel)
                                .addComponent(Team4Points))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Team2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Team2Button)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PointsLabel)
                            .addComponent(Team2Points))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(Team1Purse)
                        .addComponent(jLabel9)
                        .addComponent(Team2Purse)
                        .addComponent(jLabel11)
                        .addComponent(Team3Purse)
                        .addComponent(Team4Purse)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Team1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1ButtonActionPerformed
    timer.timerStatus(1);
    bid.Bid("Team 1");
    Button_Status.ButtonStatus("T1");
// TODO add your handling code here:
    }//GEN-LAST:event_Team1ButtonActionPerformed

    private void Team2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2ButtonActionPerformed
        // TODO add your handling code here:
        timer.timerStatus(1);
        bid.Bid("Team 2");
        Button_Status.ButtonStatus("T2");
    }//GEN-LAST:event_Team2ButtonActionPerformed

    private void Team3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team3ButtonActionPerformed
        // TODO add your handling code here:
        timer.timerStatus(1);
        bid.Bid("Team 3");
        Button_Status.ButtonStatus("T3");
    }//GEN-LAST:event_Team3ButtonActionPerformed

    private void Team4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team4ButtonActionPerformed
        // TODO add your handling code here:
        timer.timerStatus(1);
        bid.Bid("Team 4");
        Button_Status.ButtonStatus("T4");
    }//GEN-LAST:event_Team4ButtonActionPerformed

    private void EndBidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndBidButtonActionPerformed
        bid.EndBid();
    }//GEN-LAST:event_EndBidButtonActionPerformed
    
                
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuctionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuctionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuctionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuctionDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuctionDisplay().setVisible(true);
                timer.timer();
                timer.timerStatus(0);
      
                One.gen();
                One.onePlayer(0);
                
                        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel BidIncrement;
    public static javax.swing.JLabel CurrTeamPrice;
    private javax.swing.JLabel CurrentPriceLabel;
    public static javax.swing.JLabel CurrentPriceTeam;
    private javax.swing.JButton EndBidButton;
    private javax.swing.JLabel LastPriceLabel;
    public static javax.swing.JLabel LastTeamPrice;
    public static javax.swing.JLabel PlayerBasePrice;
    private javax.swing.JLabel PlayerImageLabel;
    public static javax.swing.JLabel PlayerName;
    private javax.swing.JLabel PlayerNameLabel;
    private javax.swing.JLabel PlayerNameLabel1;
    private javax.swing.JLabel PlayerNameLabel2;
    public static javax.swing.JLabel PlayerRating;
    public static javax.swing.JLabel PlayerRole;
    private javax.swing.JLabel PointsLabel;
    private javax.swing.JLabel Prev2Price;
    public static javax.swing.JLabel Prev2PriceTeam;
    public static javax.swing.JLabel PrevPriceTeam;
    public static javax.swing.JLabel PrevTeamPrice;
    private javax.swing.JLabel RemainingPlayers;
    public static javax.swing.JButton Team1Button;
    private javax.swing.JLabel Team1Label;
    public static javax.swing.JTextArea Team1PlayerList;
    public static javax.swing.JLabel Team1Points;
    private javax.swing.JLabel Team1PointsLabel;
    public static javax.swing.JLabel Team1Purse;
    public static javax.swing.JButton Team2Button;
    private javax.swing.JLabel Team2Label;
    public static javax.swing.JTextArea Team2PlayerList;
    public static javax.swing.JLabel Team2Points;
    public static javax.swing.JLabel Team2Purse;
    public static javax.swing.JButton Team3Button;
    private javax.swing.JLabel Team3Label;
    public static javax.swing.JTextArea Team3PlayerList;
    public static javax.swing.JLabel Team3Points;
    private javax.swing.JLabel Team3PointsLabel;
    public static javax.swing.JLabel Team3Purse;
    public static javax.swing.JButton Team4Button;
    private javax.swing.JLabel Team4Label;
    public static javax.swing.JTextArea Team4PlayerList;
    public static javax.swing.JLabel Team4Points;
    private javax.swing.JLabel Team4PointsLabel;
    public static javax.swing.JLabel Team4Purse;
    public static javax.swing.JLabel Timer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
